config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  root 'home#home'
  devise_for :users, skip: :registrations, controllers: {  registrations: "registrations" }
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end
  get '/new_ticket', to: 'tickets#new'
  get '/show_tickets', to: 'tickets#index'
  get '/user_dashboard', to: 'users#show'
  get '/tickets/:id',   to: 'tickets#show', as: :ticket
  get '/search', to: 'tickets#search', as: :search_tickets
  resources :comments, only: :create
  resources :users, only: [:index, :update] do
    resources :tickets, except: [:new, :index, :show, :update] do
      member do 
        put :close
      end
    end
    member do
      put :deactivate_account
      put :activate_account
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true

  belongs_to :user
  belongs_to :ticket
  has_many_attached :uploads

  after_create_commit { CommentBroadcastJob.perform_later(self) }

  def update_ticket_status!(options = {})
    options[:user].id == options[:ticket].user.id ? options[:ticket].user_response : options[:ticket].support_response
    options[:ticket].save
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @ticket = Ticket.find(params[:comment][:ticket_id])
    redirect_to ticket_path(@ticket.id), alert: 'This ticket is closed' and return if @ticket.closed?
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        @comment.update_ticket_status!(user: @comment.user, ticket: @ticket)
        UserNotifierService.new(ticket: @comment.ticket, current_user: current_user).call
        @emails = @ticket.comments.joins(:user).distinct.pluck(:email)
        @emails.push(@ticket.user.email) unless @emails.include?(@ticket.user.email)
        @emails.delete(current_user.email)
        @emails.each do |email|
          SlackService.new.call(email, @ticket.id)
        end
        format.html { redirect_to ticket_path(@ticket.id), notice: 'Comment was created' }
        format.js
      else
        format.html { redirect_to ticket_path(@ticket.id), alert: 'Couldn\'t create comment without any text' }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :ticket_id, uploads: []).merge(user_id: current_user.id)
  end
end

app/views/comments/_comment.html.erb
<div align="<%= align %>" data-comment-id="<%= comment.id %>">
  <div class="comments-section <% if align == 'right' %>darker<% end %> p-2 w-75">
    <div class="time-<%= align %>">
      <a data-toggle="tooltip" title="<%= comment.created_at.strftime("%A, %Y.%m.%d, %H:%M") %>">
        <div class="time-<%= align %>">
        <%= comment.created_at.strftime("%H:%M") %>
        </div>
      </a>
      &emsp;
    </div>
    <div align="left">
      <b class="commenter-name"><%= "#{comment.user.fullname} (#{comment.user.role.name.humanize})" %></b>
      &emsp;
      <br />
      <%= sanitize comment.body.gsub(/\n/, '<br />').html_safe %>
    </div>
     <% if comment.uploads.attached? %>
     <br />
      <table>
        <thead align="left">
          <tr>
            <th>Attachements:</th>
          </tr>
        </thead>
        <% comment.uploads.each_with_index do |upload, i| %>
          <tr><td align="left"><%= link_to("#{upload.filename}", rails_blob_path(upload, disposition: "attachment")) %></td></tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>

app/views/comments/_form.erb
<%= form_for @comment, url: comments_path, remote: true do |f| %>
  <%= f.text_area :body, :rows => 3, style: 'width:100%;', class: 'jumbotron p-1 bg-white rounded', placeholder: 'Add new comment...' %>
  <%= f.hidden_field(:user_id, value: current_user.id) %>
  <%= f.hidden_field(:ticket_id, value: @ticket.id) %>
  <div class="box">
    <p class="item" align="left">
      <%= f.label :uploads, 'Attachments' %>
      <br/>
      <%= f.file_field :uploads, multiple: true %>
    </p>
    <p class="item" align="right">
      <%= f.submit 'Add comment', class: 'btn btn-secondary' %>
    </p>
  </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.persisted? %>
   setTimeout(function() {
      $('#comment_body').val('')
      $('[data-comment-id="<%= @comment.id %>"]').remove();
      $('.commentSection').append('<%= j render partial: 'comments/comment', locals: { comment: @comment, align: 'right' } %>');
   }, 50);
<% else %>
<% end %>

app/views/comments/destroy.js.erb
$('[data-comment-id="<%= @comment.id %>"]').remove();