config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  root 'home#home'
  devise_for :users, skip: :registrations, controllers: {  registrations: "registrations" }
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end
  get '/new_ticket', to: 'tickets#new'
  get '/show_tickets', to: 'tickets#index'
  get '/user_dashboard', to: 'users#show'
  get '/tickets/:id',   to: 'tickets#show', as: :ticket
  get '/search', to: 'tickets#search', as: :search_tickets
  resources :comments, only: :create
  resources :users, only: [:index, :update] do
    resources :tickets, except: [:new, :index, :show, :update] do
      member do 
        put :close
      end
    end
    member do
      put :deactivate_account
      put :activate_account
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable,
    :validatable, :confirmable, :lockable

  validates :first_name, :last_name, presence: true
  belongs_to :role
  has_many :comments, dependent: :nullify
  has_many :tickets, dependent: :nullify

  before_validation :default_role, on: :create

  scope :unlocked,                     -> { where(locked_at: nil) }
  scope :locked,                       -> { where.not(locked_at: nil) }
  scope :ordered_by_last_name_asc,     -> { order(Arel.sql('lower(last_name) ASC')) }
  scope :ordered_by_last_name_desc,    -> { order(Arel.sql('lower(last_name) DESC')) }
  scope :ordered_by_email_asc,         -> { order(Arel.sql('lower(email) ASC')) }
  scope :ordered_by_email_desc,        -> { order(Arel.sql('lower(email) DESC')) }

  def admin?
    role.name == 'admin'
  end

  def it_support?
    role.name == 'it_support'
  end

  def om_support?
    role.name == 'om_support'
  end

  def user?
    role.name == 'user'
  end

  def support?
    om_support? || it_support? || admin?
  end

  def same_user?(user_id)
    id == user_id
  end

  def fullname
    "#{first_name} #{last_name}"
  end

  def self.filter_users(status)
    case status
    when 'locked'
      locked
    when 'unlocked'
      unlocked
    else
      all
    end
  end

  def self.sort_users(by)
    case by
    when 'last_name_asc'
      ordered_by_last_name_asc
    when 'last_name_desc'
      ordered_by_last_name_desc
    when 'email_asc'
      ordered_by_email_asc
    when 'email_desc'
      ordered_by_email_desc
    else
      all
    end
  end

  private

  def default_role
    self.role ||= Role.find_by(name: 'user')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_admin, only: %i[index update deactivate_account activate_account]

  def show
    @tickets = current_user.tickets.paginate(page: params[:page], per_page: params[:number])
  end

  def index
    @roles = Role.all.map { |role| [role.name.humanize.to_s, role.id] }
    @users = User.all
    @users = @users.filter_users(params[:filter_param]) if params[:filter_param]
    @users = @users.sort_users(params[:sorted_by]) if params[:sorted_by]
    @users = @users.paginate(page: params[:page], per_page: params[:number])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: "You have successfully changed the role of #{@user.fullname}" }
        format.js
      else
        format.html { render :index }
      end
    end
  end

  def deactivate_account
    if current_user.same_user?(params[:id].to_i)
      redirect_to(
        users_path,
        alert: 'You can not deactivate yourself'
      ) and return
    end
    @user = User.find(params[:id])
    respond_to do |format|
      @user.lock_access!(send_instructions: false)
      format.html { redirect_to users_path }
      format.js
    end
  end

  def activate_account
    if current_user.same_user?(params[:id].to_i)
      redirect_to(
        users_path,
        alert: 'You can not activate yourself'
      ) and return
    end
    @user = User.find(params[:id])
    respond_to do |format|
      @user.unlock_access!
      format.html { redirect_to users_path }
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:role_id)
  end
end

app/views/users/_lock_account_modal.erb
<button <% if current_user.id == user.id %> disabled="disabled" class="btn btn-secondary" <% else %> class="btn btn-danger" <% end %> type="button"  data-toggle="modal" data-target="#exampleModalCenter<%= user.id %>">
  Lock
</button>

<div class="modal fade" id="exampleModalCenter<%= user.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Confirmation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Do you really want to deactivate <%= user.fullname %> ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= button_to 'Lock', deactivate_account_user_path(user.id), method: :put, user: user, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<tr data-user-id="<%= user.id %>">
  <td full_name-user-id="<%= user.id %>"><%= user.fullname %></td>
  <td email-user-id="<%= user.id %>"><%= user.email %></td>
  <td>
    <%= form_for(user, url: user_path(user.id), method: :put, remote: true) do |f| %>
      <div class="input-group">
        <% if current_user.id == user.id %>
          <div class="input-group-btn">
            <%= f.select :role_id, ['Admin', 1], {}, class: 'custom-select', disabled: 'disabled' %>
          </div>
          <%= f.submit 'Save', class: 'btn btn-secondary disabled', data: { disable_with: false }, disabled: 'disabled' %>
        <% else %>
          <div class="input-group-btn">
              <%= f.select :role_id, @roles, {}, class: 'custom-select', 'data-user-select-id': "#{user.id}" %>
          </div>
          <%= f.submit 'Save', class: 'btn btn-primary', data: { disable_with: false }, 'data-user-btn-id': "#{user.id}" %>
        <% end %>
      </div>
    <% end %>
  </td>
  <% if user.access_locked? %>
    <td>
      <%= link_to 'Unlock', activate_account_user_path(user.id), method: :put, class: 'btn btn-primary' %>
    </td>
  <% else %>
    <td>
      <%= render 'lock_account_modal', user: user %>
    </td>
  <% end %>
</tr>

app/views/users/deactivate_account.js.erb
// $("#exampleModalCenter<%= @user.id %>").css({color: 'red'}).modal('hide');
$('[status-user-id="<%= @user.id %>"]').replaceWith( "<td>Status: Inactive</td>" );
$('[deactivation-button-user-id="<%= @user.id %>"]').fadeOut(1);

app/views/users/index.html.erb
<div class="container">
  <h1>Users</h1>

  <table>
    <tr>
      <th>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Results
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to '10', users_path(:number => 10, :filter_param => params[:filter_param], :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
            <%= link_to '30', users_path(:number => 30, :filter_param => params[:filter_param], :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
            <%= link_to '50', users_path(:number => 50, :filter_param => params[:filter_param], :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
          </div>
        </div>
      </th>
      <th>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Filter
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to 'All', users_path(:number => params[:number], :filter_param => "all", :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
            <%= link_to 'Locked', users_path(:number => params[:number], :filter_param => "locked", :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
            <%= link_to 'Unlocked', users_path(:number => params[:number], :filter_param => "unlocked", :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
          </div>
        </div>
      </th>
    </tr>
  </table>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name<%= link_to "<span>&#8593;</span>".html_safe, users_path(:number => params[:number], :filter_param => params[:filter_param], :sorted_by => "last_name_desc"), class: 'arrow-up' %> <%= link_to "<span>&#8595;</span>".html_safe, users_path(:number => params[:number], :filter_param => params[:filter_param], :sorted_by => "last_name_asc"), class: 'arrow-down' %> </th>
        <th>Email<%= link_to "<span>&#8593;</span>".html_safe, users_path(:number => params[:number], :filter_param => params[:filter_param], :sorted_by => "email_desc"), class: 'arrow-up' %> <%= link_to "<span>&#8595;</span>".html_safe, users_path(:number => params[:number], :filter_param => params[:filter_param], :sorted_by => "email_asc"), class: 'arrow-down' %> </th>
        <th colspan="2">Change role</th>
      </tr>
    </thead>
    <tbody>
      <% cache @users do %>
        <% @users.each do |user| %>
          <%= render 'user', user: user %>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <% if @users.any? %>
    <div>
      <%= will_paginate @users, :container => false %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <script>
  $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();   
  });
  </script>
  <h1>My tickets</h1>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Results
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to '10', user_dashboard_path(:number => 10), class: 'dropdown-item' %>
        <%= link_to '30', user_dashboard_path(:number => 30), class: 'dropdown-item' %>
        <%= link_to '50', user_dashboard_path(:number => 50), class: 'dropdown-item' %>
      </div>
    </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Status</th>
            <th scope="col">Last response</th>
            <th scope="col">Recent comments</th>
          </tr>
        </thead>
        <tbody> 
          <% if @tickets.any? %>
            <% @tickets.each do |ticket| %>
              <tr>
                <td><%= link_to ticket.title, ticket_path(id: ticket.id) %></td>
                <td>
                  <div class="<%= ticket.status.name %>">
                    <%= ticket.status.name.humanize.to_s %>
                  </div>
                </td>
                <td>
                  <% if ticket.comments.any? %>
                    <%= ticket.comments.last.updated_at.in_time_zone("Warsaw").strftime("%k:%M %d-%m-%Y") %>                
                  <% else %>
                    <%= ticket.created_at.in_time_zone("Warsaw").strftime("%k:%M %d-%m-%Y") %>
                  <% end %>
                </td>
                <td>
                  <% if ticket.comments.any? %>
                    <div class="dropdown">
                      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        See comments
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <% ticket.comments.last(6).reverse_each do |comment| %>
                          <a class="dropdown-item-text" data-toggle="tooltip" title="<%= comment.body %>">
                            <b><%= "#{comment.user.fullname}(#{comment.user.role.name})" %></b><%= "(#{comment.created_at.in_time_zone("Warsaw").strftime("%k:%M")}): #{comment.body.truncate(40, omission: '... (continued)')}" %>
                          </a>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% if @tickets.any? %>
      <div>
        <%= will_paginate @tickets, :container => false %>
      </div>
    <% end %>
</div>

app/views/users/update.js.erb
var btn = $('[data-user-btn-id="<%= @user.id %>"]');
btn.addClass('disabled');
btn.prop('disabled', 'disabled');
btn.removeClass('btn-primary');
btn.addClass('btn-secondary');
btn.prop('value', 'Saved');

setTimeout(function() {
      btn.removeClass('disabled');
      btn.removeClass('btn-secondary');
      btn.addClass('btn-primary')
      btn.prop('value', 'Save')
      btn.prop('disabled', false)
   }, 500);