config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  root 'home#home'
  devise_for :users, skip: :registrations, controllers: {  registrations: "registrations" }
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end
  get '/new_ticket', to: 'tickets#new'
  get '/show_tickets', to: 'tickets#index'
  get '/user_dashboard', to: 'users#show'
  get '/tickets/:id',   to: 'tickets#show', as: :ticket
  get '/search', to: 'tickets#search', as: :search_tickets
  resources :comments, only: :create
  resources :users, only: [:index, :update] do
    resources :tickets, except: [:new, :index, :show, :update] do
      member do 
        put :close
      end
    end
    member do
      put :deactivate_account
      put :activate_account
    end
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :department
  has_many :comments, dependent: :nullify
  belongs_to :status
  has_many_attached :uploads

  validates :note, presence: true, length: { maximum: 500 }
  validates :title, presence: true, length: { maximum: 50 }
  validates :department, presence: true

  before_validation :default_status, on: :create

  scope :it_department,                          -> { joins(:department).where(departments: { name: 'IT' }) }
  scope :om_department,                          -> { joins(:department).where(departments: { name: 'OM' }) }
  scope :ordered_by_date,                        -> { order(created_at: :desc) }
  scope :ordered_by_title_asc,                   -> { order(Arel.sql('LOWER(title) ASC')) }
  scope :ordered_by_title_desc,                  -> { order(Arel.sql('LOWER(title) DESC')) }
  scope :ordered_by_user_name_asc,               -> { joins(:user).order(Arel.sql('LOWER(users.last_name) ASC')) }
  scope :ordered_by_user_name_desc,              -> { joins(:user).order(Arel.sql('LOWER(users.last_name) DESC')) }
  scope :ordered_by_department_om,               -> { joins(:department).order('departments.name DESC') }
  scope :ordered_by_department_it,               -> { joins(:department).order('departments.name ASC') }
  scope :filtered_by_status_open,                -> { joins(:status).where(statuses: { name: 'open' }) }
  scope :filtered_by_status_support_response,    -> { joins(:status).where(statuses: { name: 'support_response' }) }
  scope :filtered_by_status_user_response,       -> { joins(:status).where(statuses: { name: 'user_response' }) }
  scope :filtered_by_status_closed,              -> { joins(:status).where(statuses: { name: 'closed' }) }

  def user_response
    self.status = find_status('user_response')
  end

  def support_response
    self.status = find_status('support_response')
  end

  def closed?
    status.name == 'closed'
  end

  def related_to_ticket?(current_user)
    user == current_user || current_user.admin? ||
      (current_user.it_support? && department.name == 'IT') ||
      (current_user.om_support? && department.name == 'OM')
  end

  def notify_users(user_ids)
    users = User.find(user_ids)
    users.each do |user|
      UserMailer.with(user: user, ticket: self).notify.deliver_later
    end
  end

  def self.find_related_tickets(current_user)
    if current_user.admin?
      all
    elsif current_user.om_support?
      om_department
    elsif current_user.it_support?
      it_department
    end
  end

  def self.filter_tickets(status)
    case status
    when 'open'
      filtered_by_status_open
    when 'closed'
      filtered_by_status_closed
    when 'user_response'
      filtered_by_status_user_response
    when 'support_response'
      filtered_by_status_support_response
    else
      all
    end
  end

  def self.sort_tickets(by)
    case by
    when 'title_asc'
      ordered_by_title_asc
    when 'title_desc'
      ordered_by_title_desc
    when 'user_name_asc'
      ordered_by_user_name_asc
    when 'user_name_desc'
      ordered_by_user_name_desc
    when 'department_om'
      ordered_by_department_om
    when 'department_it'
      ordered_by_department_it
    else
      ordered_by_date
    end
  end

  private

  def default_status
    self.status ||= find_status('open')
  end

  def find_status(name)
    Status.find_by(name: name)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    redirect_to user_dashboard_path, alert: 'Forbidden access' and return if current_user.user?
    @tickets = Ticket.find_related_tickets(current_user)
    @tickets = @tickets.filter_tickets(params[:filter_param]) if params[:filter_param]
    @tickets = if params[:sorted_by]
                 @tickets.sort_tickets(params[:sorted_by])
               else
                 @tickets.ordered_by_date
               end
    @tickets = @tickets.paginate(page: params[:page], per_page: params[:number])
  end

  def show
    @ticket = Ticket.find(params[:id])
    unless @ticket.related_to_ticket?(current_user)
      redirect_to(
        user_dashboard_path,
        alert: 'Forbidden access'
      ) and return
    end
    @comment = Comment.new(ticket_id: @ticket.id)
    @comments = @ticket.comments.order(created_at: :asc)
    @status = @ticket.status.name.humanize
  end

  def new
    @ticket = current_user.tickets.build
    @departments = Department.all.pluck(:name, :id)
  end

  def create
    @ticket = current_user.tickets.build(ticket_params)
    if @ticket.save
      @emails = if @ticket.department.name == 'IT'
                  User.joins(:role).where(roles: { name: 'it_support' }).distinct.pluck(:email)
                else
                  User.joins(:role).where(roles: { name: 'om_support' }).distinct.pluck(:email)
                end
      @emails.delete(current_user.email)
      @emails.each do |email|
        SlackService.new.call(email, @ticket.id)
      end
      redirect_to user_dashboard_path, notice: 'New ticket has been reported'
    else
      @departments = Department.all.pluck(:name, :id)
      render :new
    end
  end

  def close
    @ticket = Ticket.find(params[:id])
    status_closed = Status.find_by(name: 'closed')
    @ticket.update(status_id: status_closed.id)
    if current_user.support?
      redirect_to show_tickets_path, notice: 'Ticket closed'
    else
      redirect_to user_dashboard_path, notice: 'Ticket closed'
    end
  end

  def search
    redirect_to user_dashboard_path, alert: 'Forbidden access' and return if current_user.user?
    query = params[:query]
    @tickets = Ticket.where('title LIKE ? OR note LIKE ?', "%#{query}%", "%#{query}%")
    if current_user.it_support?
      @tickets = @tickets.it_department
    elsif current_user.om_support?
      @tickets = @tickets.om_department
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:title, :note, :status, :department_id, uploads: [])
  end
end

app/views/tickets/_lock_ticket_modal.erb
<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter<%= ticket.id %>">
  Close this ticket
</button>

<div class="modal fade" id="exampleModalCenter<%= ticket.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Confirmation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" align="left">
        Do you really want to PERMANENTLY close this ticket?
        <br />
        This operation is NOT reversible!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Back</button>
        <%= button_to 'Close ticket', close_user_ticket_path(@ticket.id), method: :put, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/tickets/_search_engine.erb
<%= form_tag search_tickets_path, method: :get, class: 'input-group' do %>
  <%= text_field_tag :query, nil, placeholder: 'Search by ticket\'s title / body', 'aria-label': 'Search', class: 'form-control' %>
  <%= submit_tag 'Search', class: 'btn btn-secondary' %>
<% end %>

app/views/tickets/_ticket.erb
<tr>
  <td><%= ticket.user.fullname %></td>
  <td><%= link_to ticket.title, ticket_path(id: ticket.id) %></td>
  <td><%= ticket.department.name %></td>
  <td>
    <% if ticket.comments.any? %>
      <%= ticket.comments.last.updated_at.in_time_zone("Warsaw").strftime("%k:%M %d-%m-%Y") %>                
    <% else %>
      <%= ticket.created_at.in_time_zone("Warsaw").strftime("%k:%M %d-%m-%Y") %>
    <% end %>
  </td>
  <td>
    <div class="<%= ticket.status.name %>">
        <%= ticket.status.name.humanize %>
    </div>
  </td>
</tr>

app/views/tickets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>All Tickets</h1>
    </div>
    <div class="col-md-4 offset-md-2 ticket-searchEngine">
      <%= render 'search_engine' %>
    </div>
  </div>

  <table>
    <tr>
      <th>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Results
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to '10', show_tickets_path(:number => 10, :filter_param => params[:filter_param], :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
            <%= link_to '30', show_tickets_path(:number => 30, :filter_param => params[:filter_param], :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
            <%= link_to '50', show_tickets_path(:number => 50, :filter_param => params[:filter_param], :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
          </div>
        </div>
      </th>
      <th>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Filter by status
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to 'All', show_tickets_path(:number => params[:number], :filter_param => "all", :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Open', show_tickets_path(:number => params[:number], :filter_param => "open", :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
            <%= link_to 'Support response', show_tickets_path(:number => params[:number], :filter_param => "support_response", :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
            <%= link_to 'User response', show_tickets_path(:number => params[:number], :filter_param => "user_response", :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>
            <%= link_to 'Closed', show_tickets_path(:number => params[:number], :filter_param => "closed", :sorted_by => params[:sorted_by]), class: 'dropdown-item' %>                                  
          </div>
        </div>
      </th>
    </tr>
  </table>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Author<%= link_to "<span>&#8593;</span>".html_safe, show_tickets_path(:number => params[:number], :filter_param => params[:filter_param], :sorted_by => "user_name_desc"), class: 'arrow-up' %> <%= link_to "<span>&#8595;</span>".html_safe, show_tickets_path(:number => params[:number], :filter_param => params[:filter_param], :sorted_by => "user_name_asc"), class: 'arrow-down' %> </th>
        <th scope="col">Title<%= link_to "<span>&#8593;</span>".html_safe, show_tickets_path(:number => params[:number], :filter_param => params[:filter_param], :sorted_by => "title_desc"), class: 'arrow-up' %> <%= link_to "<span>&#8595;</span>".html_safe, show_tickets_path(:number => params[:number], :filter_param => params[:filter_param], :sorted_by => "title_asc"), class: 'arrow-down' %> </th>
        <th scope="col">Department<%= link_to "<span>&#8593;</span>".html_safe, show_tickets_path(:number => params[:number], :filter_param => params[:filter_param], :sorted_by => "department_it"), class: 'arrow-up' %> <%= link_to "<span>&#8595;</span>".html_safe, show_tickets_path(:number => params[:number], :filter_param => params[:filter_param], :sorted_by => "department_om"), class: 'arrow-down' %> </th>
        <th scope="col">Last response</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <% @tickets.each do |ticket| %>
        <% cache ticket do %>
          <%= render 'ticket', ticket: ticket %>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <% if @tickets.any? %>
    <div>
      <%= will_paginate @tickets, :container => false %>
    </div>
  <% end %>
</div>

app/views/tickets/new.html.erb
<% if @ticket.errors.any? %>
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3 alert alert-danger">
        <h5><%= pluralize(@ticket.errors.count, 'error') %> prohibited this ticket from being saved</h5>
        <ul>
        <% @ticket.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1><center> Create new ticket </center></h1> 
      <%= form_for @ticket, url: user_tickets_path(current_user.id) do |f| %>
        <%= f.label :department_id %>
        <%= f.select :department_id, @departments, {}, class: 'custom-select' %>
        <hr />
        <%= f.label :title %>
        <%= f.text_field :title, maxlength: '50', class: 'form-control' %>
        <hr />
        <%= f.label :note , 'Body' %>
        <%= f.text_area :note, class: 'form-control', cols: '16', rows: '6' %>
        <hr />
        <%= f.label :uploads , 'Attachments' %><br/>
        <%= f.file_field :uploads, class: 'form-control', multiple: true, class: 'btn btn-default' %>
        <hr />
        <%= f.submit 'Create', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/tickets/search.html.erb
<div class="container">
  <div class="row searchEngine">
    <div class="col-md-6">
      <h2>Search results</h1> 
    </div>
    <div class="col-md-4 offset-md-2">
      <%= render 'search_engine' %>
    </div>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Author</th>
        <th scope="col">Title</th>
        <th scope="col">Department</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <% @tickets.each do |ticket| %>
          <%= render 'ticket', ticket: ticket %>
      <% end %>
      <% unless @tickets.any? %>
        <tr><td colspan="4">Your query did not match any results</td></tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tickets/show.html.erb
<div class="container">
  <br />
  <script>
  $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();   
  });
  </script>

  <% if @ticket.closed? %>
    <div class="ticket-closed-message mb-2 bg-danger text-white">
      <tr>
        <td class="align-text-bottom">
          <h2>
            <p class="text-center">THIS TICKET IS CLOSED</p>
          </h2>
        </td>
      </tr>
    </div>
  <% end %>
  <div class="jumbotron p-2 bg-light">
    <div class="tickets-display" align="center">
      <table class="ticket-properties-table">
        <thead>
          <tr>
            <th><b>Title:</b></th>
            <th><b>User:</b></th>
            <th><b>Created at:</b></th>
            <th><b>Status:</b></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @ticket.title %></td>
            <td><%= @ticket.user.fullname %></td>
            <td><%= @ticket.created_at.strftime("%Y.%m.%d %H:%M") %></td>
            <td><%= @status %></td>
            <td>
              <% unless @ticket.closed? %>
                <%= render 'lock_ticket_modal', ticket: @ticket %>
              <% end %>
            </td>
        </tbody>
      </table>
    </div>
    <hr/>

    <div class="ticket-note text-left">
      <p><%= sanitize @ticket.note.gsub(/\n/, '<br />').html_safe %></p>
    </div>
    <% if @ticket.uploads.attached? %>
    <hr />
      <div class="ticket-attachements">
        <table>
          <thead>
            <th>Attachements:</th>
          </thead>
          <tbody>
            <% @ticket.uploads.each_with_index do |upload, i| %>
              <tr><td><%= link_to("#{upload.filename}", rails_blob_path(upload, disposition: "attachment")) %></td></tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>

  <div class="jumbotron p-2 bg-light">
  <div class="commentSection" data-ticket-id="<%= @ticket.id %>">
  <% @comments.each do |comment| %>
    <% if comment.user.id == current_user.id %>
      <%= render 'comments/comment', comment: comment, align: 'right' %>
    <% else %>
      <%= render 'comments/comment', comment: comment, align: 'left' %> 
    <% end %> 
  <% end %>
  </div>
  <% unless @ticket.closed? %>
    <br />
    <div class="tickets-display">
      <%= render 'comments/form' %>
    </div>
  <% end %>
</div>