config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  root 'home#home'
  devise_for :users, skip: :registrations, controllers: {  registrations: "registrations" }
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end
  get '/new_ticket', to: 'tickets#new'
  get '/show_tickets', to: 'tickets#index'
  get '/user_dashboard', to: 'users#show'
  get '/tickets/:id',   to: 'tickets#show', as: :ticket
  get '/search', to: 'tickets#search', as: :search_tickets
  resources :comments, only: :create
  resources :users, only: [:index, :update] do
    resources :tickets, except: [:new, :index, :show, :update] do
      member do 
        put :close
      end
    end
    member do
      put :deactivate_account
      put :activate_account
    end
  end
end

app/views/layouts/partials/_flash.html.haml
- if alert 
	.alert.alert-danger
		Alert: #{alert}
- if notice
	.alert.alert-success
		Success: #{notice}

app/views/layouts/partials/_footer.html.erb
<footer class="footer">
  <div class="footer-copyright text-center text-black-50 py-3">Binar::Apps Internship 2018 <span class="spade">&#9824;</span> Bartosz Kowalewski - Piotr Hacaś - Tomasz Podsiadły - Michał Chudzik <span class="spade">&#9824;</span></div>
</footer>

app/views/layouts/partials/_navbar.html.erb
<% if user_signed_in? && current_user.user? %>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <span class="navbar-brand"><%= link_to 'Tickets App', user_dashboard_path, class: 'navbar-brand' %></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
         <%= link_to 'New Ticket', new_ticket_path, class: 'nav-link' %>
        </li>
          <li class="nav-item active">
            <%= link_to 'My Tickets', user_dashboard_path, class: 'nav-link' %>
          </li>
      </ul>

      <ul class="navbar-nav mr-sm-2">
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.fullname %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </nav>

<% elsif user_signed_in? && (current_user.it_support? || current_user.om_support?) %>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <span class="navbar-brand"><%= link_to 'Tickets App', user_dashboard_path, class: 'navbar-brand' %></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
         <%= link_to 'New Ticket', new_ticket_path, class: 'nav-link' %>
        </li>
          <li class="nav-item active">
            <%= link_to 'My Tickets', user_dashboard_path, class: 'nav-link' %>
          </li>
          <% if current_user.it_support? %>
            <li class="nav-item active">
              <%= link_to 'IT Tickets', show_tickets_path, class: 'nav-link' %>
            </li>
          <% elsif current_user.om_support? %>
            <li class="nav-item active">
              <%= link_to 'OM Tickets', show_tickets_path, class: 'nav-link' %>
            </li>
          <% end %>
      </ul>

      <ul class="navbar-nav mr-sm-2">
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.fullname %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </nav>

  <% elsif user_signed_in? && current_user.admin? %>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <span class="navbar-brand"><%= link_to 'Tickets App', user_dashboard_path, class: 'navbar-brand' %></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
         <%= link_to 'New Ticket', new_ticket_path, class: 'nav-link' %>
        </li>
          <li class="nav-item active">
            <%= link_to 'My Tickets', user_dashboard_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'All Tickets', show_tickets_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Users', users_path, class: 'nav-link' %>
          </li>
      </ul>

      <ul class="navbar-nav mr-sm-2">
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.fullname %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </nav>

<% elsif !user_signed_in? %>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <span class="navbar-brand"><%= link_to 'Tickets App', new_user_session_path, class: 'navbar-brand' %></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
         <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
          <li class="nav-item active">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
      </ul>
    </div>
  </nav>

<% end %>